# Generated by Django 4.1 on 2022-08-15 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0002_alter_order_number_alter_rubleprice_exchange_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.date.today, verbose_name="срок поставки"
            ),
        ),
    ]
