# Generated by Django 4.1 on 2022-08-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0003_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubleprice",
            name="currency_exchange_code",
            field=models.CharField(
                default="USD",
                max_length=3,
                unique=True,
                verbose_name="Exchange Currency Code",
            ),
        ),
    ]
