version: '3.7'
services:
  database:
    environment:
      POSTGRES_DB: orders_puller_db
      POSTGRES_PASSWORD: orders_puller_db_password_1
    image: postgres:14.1
    ports:
      - 127.0.0.1:5432:5432/tcp
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
  web:
    build: .
    command: sh -c "service cron start /&& python manage.py crontab add && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - CORE_DATABASE_URL=psql://postgres:orders_puller_db_password_1@database:5432/orders_puller_db
    depends_on:
      - database
volumes:
  pg_data: {}